- name: Install sway package
  community.general.pacman:
    name:
      - sway
      - swaybg
      - rofi-wayland
      - chromium
    state: latest
    update_cache: true
- name: Create .config/sway director
  ansible.builtin.file:
    path: "/home/luis/.config/sway"
    state: directory
    owner: luis
    group: luis
- name: copy config file
  copy:
    src: templates/config
    dest: /home/luis/.config/sway/config
- name: copy bar script
  copy:
    src: templates/swaybar.sh
    dest: /home/luis/.config/sway/status.sh
    mode: 0755
    owner: luis
    group: luis
- name: copy wallpaper
  copy:
    src: templates/arch.png
    dest: /home/luis/.config/sway/wallpaper.png
- name: copy profile
  copy:
    src: templates/profile.sh
    dest: /home/luis/.zprofile
    mode: 0755
    owner: luis
    group: luis