- name: Install base packages
  community.general.pacman:
    name:
      - linux
      - linux-lts
      - openssh
      - vim
      - python
      - htop
      - zsh
      - git
    state: latest
    update_cache: true