- name: Install base packages
  community.general.pacman:
    name:
      - linux
      - linux-lts
      - openssh
      - vim
      - python
      - htop
      - zsh
      - git
      - flatpak
      - pipewire-pulse
      - xdg-desktop-portal-wlr
      - ansible
      - fuse2
    state: latest
    update_cache: true
